language: java

services:
  - docker

before_install:
- docker pull kafkamanager/kafka-manager:3.0.0.4
- docker tag kafkamanager/kafka-manager:3.0.0.4 demo.goharbor.io/qeesung/kafkamanager/kafka-manager:3.0.0.4
- docker push demo.goharbor.io/qeesung/kafkamanager/kafka-manager:3.0.0.4

install:
  - echo "nice to meet you"
  - env
  - printenv
