version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      - run: env && echo ${username}
  test:
    docker:
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      - run: env && echo "username is ${username}" && echo qeesung && echo xxxxung
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
